on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - devel

jobs:
          
  sonarqube:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Run testing suite
        run: make coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PROJECT_ID: ${{ github.event.repository.name }}
